services:
  - type: web
    name: uzhydromet-forecast
    runtime: python
    rootDir: app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app -c gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PORT
        value: "10000"
